### PR TITLE
Improve templating

### PR DESCRIPTION
**Pull request by chriskuehl**
This improves the templating using Jinja, and makes it easier for us to potentially have more base images if we desire to.

At least to start, `theocf/debian:jessie` (and similar) would be our base images, but we might eventually add others (e.g. a general-purpose package builder image).

More specific images (e.g. for ocfweb) wouldn't go in this repo, and instead would be built with the application. This is only for general-purpose ones.

This also drops the wheezy image, we officially no longer support it.

@kpengboy @matthew-mcallister

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
Why commit the Dockerfile template output, if I might ask?

**Comment by chriskuehl** [comment]
Automated builds on dockerhub require the dockerfiles to be checked in, you can't run anything to template them out. It really sucks. 

Since we'll probably soon build these on our Jenkins instead, we could stop doing that.

**Comment by matthew-mcallister** [comment]
OK. Might want to add a make target to build the docker images too, then.

**Comment by chriskuehl** [comment]
yeah, we can do that when we're ready to start building on jenkins (currently we don't even have docker support in jenkins, so it will take some more effort first)

**Comment by kpengboy** [comment]
RIP, wheezy is still supported upstream and it's little extra work to continue offering it...

More things:
 - Can we use dumb-init from the repos for stretch and sid?
 - If we're going to run our own Docker image builds on Jenkins, then we should consider creating additional tags `theocf/debian:testing` and `theocf/debian:unstable`.

**Comment by chriskuehl** [comment]
Why do you want wheezy? It is just technical debt, let it die. We don't use it.

Feel free to make things more complicated to include dumb-init from the repos if you think it is useful (but imo it is not, just wait until we drop jessie to do that).

**Pull request merged**
